##########
# Simple #
##########

# Bigger scrollback
set-option -g history-limit 655350

# Keep path when splitting panes
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

##########
# Modern #
##########

# TERM
set -s default-terminal "tmux-256color"

# Escape features
set -s set-clipboard on
set -s focus-events on
set -s extended-keys on

# Explicit passthrough
set -g allow-passthrough on

# Update title
set -g allow-set-title on
set -g allow-rename on

# Fullscreen behaviour
set -g alternate-screen on

# Modern capabilities
set -as terminal-features ",xterm-*:RGB,clipboard,ccolour,cstyle,extkeys,focus,hyperlinks,osc7,strikethrough,sync,title"
set -as terminal-features ",vte*:RGB,clipboard,ccolour,cstyle,extkeys,focus,hyperlinks,osc7,strikethrough,sync,title"
set -as terminal-features ",foot*:RGB,clipboard,ccolour,cstyle,extkeys,focus,hyperlinks,osc7,strikethrough,sync,title"
set -as terminal-features ",alacritty*:RGB,clipboard,ccolour,cstyle,extkeys,focus,hyperlinks,osc7,strikethrough,sync,title"
set -as terminal-features ",kitty*:RGB,clipboard,ccolour,cstyle,extkeys,focus,hyperlinks,osc7,strikethrough,sync,title"
set -as terminal-features ",wezterm*:RGB,clipboard,ccolour,cstyle,extkeys,focus,hyperlinks,osc7,strikethrough,sync,title"
set -as terminal-features ",ghostty*:RGB,clipboard,ccolour,cstyle,extkeys,focus,hyperlinks,osc7,strikethrough,sync,title"

# Preserve
set -ga update-environment " WAYLAND_DISPLAY DISPLAY XAUTHORITY"
set -ga update-environment " XDG_SESSION_TYPE XDG_CURRENT_DESKTOP XDG_RUNTIME_DIR"
set -ga update-environment " DBUS_SESSION_BUS_ADDRESS SSH_AUTH_SOCK SSH_AGENT_PID SSH_CONNECTION SSH_TTY"
set -ga update-environment " COLORTERM VTE_VERSION TERM_PROGRAM TERM_PROGRAM_VERSION"

#########
# Theme #
#########

set -g status on
set -g status-position bottom
set -g status-interval 1
set -g status-justify centre
set -g status-left-length 80
set -g status-right-length 150
set -g status-style "fg=default,bg=default"

# [session] [user] [window:pane]
set -g status-left "#[fg=default,bg=default,bold][#[fg=blue,bg=default,bold]#S#[fg=default,bg=default,bold]]#[default] #[fg=default,bg=default,bold][#[fg=green,bg=default,bold]#(whoami)#[fg=default,bg=default,bold]]#[default] #[fg=default,bg=default,bold][#[fg=magenta,bg=default,bold]#I:#P#[fg=default,bg=default,bold]]#[default] "

# [time] [date] [host]
set -g status-right " #[fg=default,bg=default,bold][#[fg=green,bg=default,bold]%H:%M:%S#[fg=default,bg=default,bold]]#[default] #[fg=default,bg=default,bold][#[fg=yellow,bg=default,bold]%d/%m/%y#[fg=default,bg=default,bold]]#[default] #[fg=default,bg=default,bold][#[fg=yellow,bg=default,bold]#H#[fg=default,bg=default,bold]]#[default]"

# Window List
set -g window-status-separator " "
set -g window-status-format " #[fg=default,bg=default]#I - #W#[default] "
set -g window-status-current-format "#[fg=default,bg=default,bold][#[fg=blue,bg=default,bold]#I - #W#[fg=default,bg=default,bold]]#[default]"

set -g window-status-style "fg=default,bg=default"
set -g window-status-current-style "fg=default,bg=default,bold"
set -g window-status-activity-style "fg=default,bg=default"
set -g window-status-bell-style "fg=default,bg=default"

# Overall

set -g message-style "fg=default,bg=default"
set -g message-command-style "fg=default,bg=default"
set -g mode-style "fg=default,bg=default,bold"
set -g copy-mode-match-style "fg=default,bg=default"
set -g copy-mode-current-match-style "fg=default,bg=default"
set -g cursor-colour default

# Borders
set -g pane-border-style "fg=default,bg=default"
set -g pane-active-border-style "fg=blue,bg=default,bold"

# Pane
set -g display-panes-colour default
set -g display-panes-active-colour default

# Block
set -g clock-mode-style 24-with-seconds
set -g clock-mode-colour white
